menu_items:
    - id: gist_accounting_menu
      acl: gist_accounting.menu
      label: Accounting
      icon: fa-money
    - id: gist_accounting_banks_index
      acl: gist_accounting_banks.menu
      label: Banks
      parent: gist_accounting_menu
    - id: gist_accounting_bank_accounts_index
      acl: gist_accounting_bank_accounts.menu
      label: Bank Accounts
      parent: gist_accounting_menu


    - id: gist_terminals_menu
      acl: gist_terminals.menu
      label: Terminals
      icon: fa-credit-card
    - id: gist_terminals_terminal_index
      acl: gist_terminals_terminal.menu
      label: Terminal
      parent: gist_terminals_menu
    - id: gist_terminals_terminal_operator_index
      acl: gist_terminals_terminal_operator.menu
      label: Terminal Operator
      parent: gist_terminals_menu