#parameters:
#    Gist_grid.example.class: Gist\GridBundle\Example

services:
    Gist_grid:
        class: Gist\GridBundle\Model\Factory
        arguments:
            em: "@doctrine.orm.entity_manager"

#    Gist_grid.example:
#        class: %Gist_grid.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
