parameters:
#    hris_template.example.class: Hris\TemplateBundle\Example

services:
#    hris_template.example:
#        class: %hris_template.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
