services:
    gist_core.table_name_subscriber:
        class: Gist\CoreBundle\Model\TableNameSubscriber
        tags:
            - { name: doctrine.event_subscriber }
        
#    gist_core.example:
#        class: Gist\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
