gist_inv_damaged_items_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:index }

gist_inv_damaged_items_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:addForm }

gist_inv_damaged_items_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:DamagedItems:addSubmit }

gist_inv_damaged_items_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:editForm }

gist_inv_damaged_items_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:DamagedItems:editSubmit }

gist_inv_damaged_items_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:delete }

gist_inv_damaged_items_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:grid }

gist_inv_damaged_items_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:ajaxGet }

gist_inv_damaged_items_print:
    pattern: /print/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:printPDF }

#    FOR POS
gist_inv_damaged_items_get_from_pos:
    path:     /get/from/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getSentFromPOS }

gist_inv_damaged_items_get_to_pos:
    path:     /get/to/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getSentToPOS }

gist_inv_damaged_items_get_location_options:
    path:     /get/loc_options/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getLocationOptions }

gist_inv_damaged_items_get_data:
    path:     /get/data/{id}/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getPOSFormData }

gist_inv_damaged_items_get_data_entries:
    path:     /get/data_entries/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getPOSFormDataEntries }

gist_inv_damaged_items_update_status:
    path:     /update_status/{id}/{userId}/{status}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:updatePOSDamagedItems }

gist_inv_damaged_items_add_new:
    path:     /add_new/{src}/{dest}/{user}/{description}/{entries}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:addPOSDamagedItems }

gist_inv_damaged_items_ajax_grid:
    path:    /search_product/ajax
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:gridSearchProduct }

gist_inv_damaged_items_search_ajax_grid:
    path:    /search_product/ajax2/{category}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:gridSearchProduct, category: null }

gist_inv_damaged_items_entry_status_change:
    path:    /entry/status/{id}/{status}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:statusUpdate, id: null, status: null }