gist_inv_damaged_items_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:index }

gist_inv_damaged_items_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:addForm }

gist_inv_damaged_items_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:DamagedItems:addSubmit }

gist_inv_damaged_items_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:editForm }

gist_inv_damaged_items_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:DamagedItems:editSubmit }

gist_inv_damaged_items_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:delete }

gist_inv_damaged_items_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:grid }

gist_inv_damaged_items_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:ajaxGet }

gist_inv_damaged_items_print:
    pattern: /print/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:printPDF }