gist_inv_existing_stock_index:
    pattern: /list/{inv_type}/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:index, inv_type: null, pos_loc_id: null }

gist_inv_existing_stock_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:addForm }

gist_inv_existing_stock_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:ExistingStock:addSubmit }

gist_inv_existing_stock_summary_ajax_grid:
    path:    /summary_table/ajax
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:gridSearchSummary }

gist_inv_existing_stock_receive_return_form:
    pattern: /receive/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:viewFormReceive }

gist_inv_existing_stock_submit_return_form:
    pattern: /receive/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:ExistingStock:submitFormReceive }

gist_inv_existing_stock_add_return_form:
    pattern: /add_return/{ids}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:addFormReturn }

gist_inv_existing_stock_add_return_submit:
    pattern: /add_return/{ids}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:ExistingStock:addReturnSubmit }

gist_inv_existing_stock_add_entries_form:
    pattern: /add_entries
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:addFormEntries }

gist_inv_existing_stock_add_entries_submit:
    pattern: /add_entries
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:ExistingStock:addSubmitEntries }

gist_inv_existing_stock_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:editForm }

gist_inv_existing_stock_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:ExistingStock:editSubmit }

gist_inv_existing_stock_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:delete }

gist_inv_existing_stock_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:grid }

gist_inv_existing_stock_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:ajaxGet }

gist_inv_existing_stock_print:
    pattern: /print/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:printPDF }

#    FOR POS
gist_inv_existing_stock_get_from_pos:
    path:     /get/from/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:getSentFromPOS }

gist_inv_existing_stock_get_to_pos:
    path:     /get/to/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:getSentToPOS }

gist_inv_existing_stock_get_location_options:
    path:     /get/loc_options/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:getLocationOptions }

gist_inv_existing_stock_get_data:
    path:     /get/data/{id}/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:getPOSFormData }

gist_inv_existing_stock_get_data_entries:
    path:     /get/data_entries/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:getPOSFormDataEntries }

gist_inv_existing_stock_update_status:
    path:     /update_status/{id}/{userId}/{status}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:updatePOSExistingStock }

gist_inv_existing_stock_add_new:
    path:     /add_new/{src}/{dest}/{user}/{description}/{entries}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:addPOSExistingStock }

gist_inv_existing_stock_ajax_grid:
    path:    /search_product/ajax
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:gridSearchProduct }

gist_inv_existing_stock_search_ajax_grid:
    path:    /search_product/ajax2/{category}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:gridSearchProduct, category: null }

gist_inv_existing_stock_entry_status_change:
    path:    /entry/status/{id}/{status}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:statusUpdate, id: null, status: null }