gist_inv_open_tester_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:OpenTester:index }

gist_inv_open_tester_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:OpenTester:addForm }

gist_inv_open_tester_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:OpenTester:addSubmit }

gist_inv_open_tester_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:OpenTester:editForm }

gist_inv_open_tester_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:OpenTester:editSubmit }

gist_inv_open_tester_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:OpenTester:delete }

gist_inv_open_tester_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:OpenTester:grid }

gist_inv_open_tester_add_entries_form:
    pattern: /add_entries
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:OpenTester:addFormEntries }

gist_inv_open_tester_add_entries_submit:
    pattern: /add_entries
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:OpenTester:addSubmitEntries }
