cat_inv_prod_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Product:index }

cat_inv_prod_submit:
    pattern: /list
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:Product:applyPriceChanges }

cat_inv_prod_index_filter:
    pattern: /list/{filter}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Product:index }


cat_inv_prod_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Product:addForm }

cat_inv_prod_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:Product:addSubmit }

cat_inv_prod_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Product:editForm }

cat_inv_prod_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:Product:editSubmit }

cat_inv_prod_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Product:delete }

# grid
cat_inv_prod_stock_grid:
    pattern: /grid/{id}/stock
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Product:stockGrid }

cat_inv_prod_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Product:grid }

# ajax 
cat_inv_prod_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Product:ajaxGet }

cat_inv_pur_prod_ajax_get:
    pattern: /ajax/purchasing/{id}/{supplier_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Product:ajaxPurGet }

cat_inv_prod_ajax_get_by:
    pattern: /ajax/product
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Product:ajaxGetBy }

cat_inv_prod_ajax_add:
    pattern: /ajax/add
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:Product:ajaxAdd }

#cat_inv_prod_ajax_get:
#    pattern: /ajax/product/{id}
#    methods: [GET]
#    defaults: { _controller: GistInventoryBundle:Product:ajaxGet }

cat_inv_prod_ajax_wh_stock:
    pattern: /ajax/product/{prod_id}/warehouse/{wh_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Product:ajaxGetWarehouseStock }

# upload
cat_inv_prod_upload:
    pattern: /upload/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:Product:upload }

cat_inv_prod_upload2:
    pattern: /upload2/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Product:upload2 }

cat_inv_prod_upload_delete:
    pattern: /image/delete/{id}/{loop}
    defaults: { _controller: GistInventoryBundle:Product:deleteImage }


# export csv
cat_inv_prod_export:
    pattern: /csv
    defaults: { _controller: GistInventoryBundle:Product:csv }
