cat_inv_product_type_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ProductType:index }

cat_inv_product_type_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ProductType:addForm }

cat_inv_product_type_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:ProductType:addSubmit }

cat_inv_product_type_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ProductType:editForm }

cat_inv_product_type_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:ProductType:editSubmit }

cat_inv_product_type_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ProductType:delete }

cat_inv_product_type_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ProductType:grid }
