parameters:
#    gist_flot.example.class: Gist\FlotBundle\Example

services:
#    gist_flot.example:
#        class: %gist_flot.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
