services:
    hris_notify:
        class: Hris\NotificationBundle\Model\NotificationManager
        arguments: ["@doctrine.orm.entity_manager", "@service_container","@security.context" ]
    kernel.listener.notification.event:
        class: Hris\NotificationBundle\Model\NotificationListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: notification.event, method: onNotify }