acl:
    - category: HRIS
      entries:
        - id: cat_hris.menu
          label: "Menu"
    - category: User
      entries:
        - id: cat_user_user.menu
          label: "Menu"
        - id: cat_user_user.view
          label: "View"
        - id: cat_user_user.add
          label: "Add"
        - id: cat_user_user.edit
          label: "Edit"
        - id: cat_user_user.delete
          label: "Delete"
    - category: Position
      entries:
        - id: cat_user_group.menu
          label: "Menu"
        - id: cat_user_group.view
          label: "View"
        - id: cat_user_group.add
          label: "Add"
        - id: cat_user_group.edit
          label: "Edit"
        - id: cat_user_group.delete
          label: "Delete"
    - category: Department
      entries:
        - id: cat_user_department.menu
          label: "Menu"
        - id: cat_user_department.view
          label: "View"
        - id: cat_user_department.add
          label: "Add"
        - id: cat_user_department.edit
          label: "Edit"
        - id: cat_user_department.delete
          label: "Delete"
    - category: Items List
      entries:
        - id: cat_user_items_list.menu
          label: "Menu"
        - id: cat_user_items_list.view
          label: "View"
        - id: cat_user_items_list.add
          label: "Add"
        - id: cat_user_items_list.edit
          label: "Edit"
        - id: cat_user_items_list.delete
          label: "Delete"
