parameters:
#    gist_user.example.class: Gist\UserBundle\Example

services:
    gist_acl:
        class: Gist\UserBundle\Model\ACLManager
        arguments: ["@service_container"]
    gist_user:
        class: Gist\UserBundle\Model\UserManager
        arguments:
            em: "@doctrine.orm.entity_manager"
#    gist_user.example:
#        class: %gist_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
