gist_pos_index:
    path:     /pos
    defaults: { _controller: GistPOSBundle:POS:index }

gist_pos_index_load:
    path:     /pos/{transaction_display_id}
    defaults: { _controller: GistPOSBundle:POS:indexLoad }

gist_main_sync_pos_data:
    path:     /pos/sync_data
    defaults: { _controller: GistPOSBundle:POS:syncData }

gist_main_clock_tap:
    path:     /pos/clock_tap/{type}
    defaults: { _controller: GistPOSBundle:POS:clock }

gist_main_index:
    path:     /admin_menu
    defaults: { _controller: GistPOSBundle:POS:landing }

gist_pos_menu_index:
    path:     /
    defaults: { _controller: GistPOSBundle:POS:posMenu }


# POS AJAX
gist_pos_get_frozen_transactions:
    path:     /pos/get_frozen_transactions
    methods: [GET]
    defaults: { _controller: GistPOSBundle:POS:getFrozenTransactions }

gist_pos_save_transaction:
    path:     /pos/save_transaction/{id}/{display_id}/{total}/{balance}/{type}/{customer_id}/{status}/{tax_rate}/{orig_vat_amt}/{new_vat_amt}/{orig_amt_net_vat}/{new_amt_net_vat}/{tax_coverage}/{cart_min}/{orig_cart_total}/{new_cart_total}/{bulk_type}/{transaction_mode}/{transaction_cc_interest}/{transaction_ea}/{deposit_amount}/{deposit_amt_net_vat}/{deposit_vat_amt}/{balance_amt_net_vat}/{balance_vat_amt}
    methods: [GET]
    defaults: { _controller: GistPOSBundle:POS:saveTransaction }

gist_pos_save_item:
    path:     /pos/save_item/{trans_sys_id}/{prod_id}/{prod_name}/{orig_price}/{min_price}/{adjusted_price}/{discount_type}/{discount_value}/{barcode}/{item_code}/{is_issued}
    methods: [GET]
    defaults: { _controller: GistPOSBundle:POS:saveTransactionItems }

gist_pos_save_payment: 
    path:     /pos/save_payment/{trans_sys_id}/{payment_type}/{amount}/{control_number}/{bank}/{terminal_operator}/{interest}/{terms}/{account_number}/{payee}/{payor}/{expiry}/{cvv}
    methods: [GET]
    defaults: { _controller: GistPOSBundle:POS:saveTransactionPayments }

gist_pos_print_receipt:
    path:    /pos/print_receipt/{id}
    methods: [GET]
    defaults: { _controller: GistPOSBundle:POS:printReceipt }

# SETTINGS
gist_pos_settings:
    path:     /settings
    methods: [GET]
    defaults: { _controller: GistPOSBundle:Settings:index }

gist_pos_settings_save:
    path:     /settings
    methods: [POST]
    defaults: { _controller: GistPOSBundle:Settings:indexSubmit }

gist_pos_settings_sync_users:
    path:     /settings/sync_users
    methods: [GET]
    defaults: { _controller: GistPOSBundle:Settings:syncUsers }

gist_pos_settings_sync_customers:
    path:     /settings/sync_customers
    methods: [GET]
    defaults: { _controller: GistPOSBundle:Settings:syncCustomers }

# REPORTS
gist_pos_reports:
    path:     /reports
    methods: [GET]
    defaults: { _controller: GistPOSBundle:Reports:index }

gist_pos_reports_edit_form:
    pattern: /report/{id}
    methods: [GET]
    defaults: { _controller: GistPOSBundle:Reports:editForm }
gist_pos_reports_grid:
    pattern: /reports/grid
    methods: [GET]
    defaults: { _controller: GistPOSBundle:Reports:grid }

gist_pos_quote_to_sale:
    pattern: /reports/quote_to_sale/{id}
    methods: [GET]
    defaults: { _controller: GistPOSBundle:POS:quoteToSale }

gist_pos_delete_transaction:
    pattern: /reports/delete_transaction/{id}
    methods: [GET]
    defaults: { _controller: GistPOSBundle:POS:deleteTransaction }

gist_pos_reports_grid_ajax:
    path:    /reports/ajax/{receipt_number}/{date_from}/{date_to}/{mode}
    defaults: { _controller: GistPOSBundle:Reports:gridSalesHistory,receipt_number: null, date_from: null, date_to: null, mode: null }

gist_pos_split_transaction_form:
    pattern: /reports/split_transaction/{id}
    methods: [GET]
    defaults: { _controller: GistPOSBundle:Reports:splitForm }

gist_pos_split_transaction_form_submit:
    pattern: /reports/split_transaction/{id}
    methods: [POST]
    defaults: { _controller: GistPOSBundle:Reports:splitFormSubmit }