parameters:
#    gist_manufacturing.example.class: Gist\ManufacturingBundle\Example

services:
#    gist_manufacturing.example:
#        class: %gist_manufacturing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
