#AREA
gist_loc_areas_index:
    pattern: /areas
    methods: [GET]
    defaults: { _controller: GistLocationBundle:Areas:index }

gist_loc_areas_add_form:
    pattern: /area
    methods: [GET]
    defaults: { _controller: GistLocationBundle:Areas:addForm }

gist_loc_areas_add_submit:
    pattern: /area
    methods: [POST]
    defaults: { _controller: GistLocationBundle:Areas:addSubmit }

gist_loc_areas_edit_form:
    pattern: /area/{id}
    methods: [GET]
    defaults: { _controller: GistLocationBundle:Areas:editForm }

gist_loc_areas_edit_submit:
    pattern: /area/{id}
    methods: [POST]
    defaults: { _controller: GistLocationBundle:Areas:editSubmit }

gist_loc_areas_delete:
    pattern: /area/{id}/delete
    methods: [GET]
    defaults: { _controller: GistLocationBundle:Areas:delete }

gist_loc_areas_grid:
    pattern: /areas/grid
    methods: [GET]
    defaults: { _controller: GistLocationBundle:Areas:grid }


gist_loc_areas_group_view:
    pattern: /area/group/{id}
    methods: [GET]
    defaults: { _controller: GistLocationBundle:Areas:viewGroup }

#POS LOCS
gist_loc_pos_locations_index:
    pattern: /pos_locations
    methods: [GET]
    defaults: { _controller: GistLocationBundle:POSLocations:index }

gist_loc_pos_locations_add_form:
    pattern: /pos_location
    methods: [GET]
    defaults: { _controller: GistLocationBundle:POSLocations:addForm }

gist_loc_pos_locations_add_submit:
    pattern: /pos_location
    methods: [POST]
    defaults: { _controller: GistLocationBundle:POSLocations:addSubmit }

gist_loc_pos_locations_edit_form:
    pattern: /pos_location/{id}
    methods: [GET]
    defaults: { _controller: GistLocationBundle:POSLocations:editForm }

gist_loc_pos_locations_edit_submit:
    pattern: /pos_location/{id}
    methods: [POST]
    defaults: { _controller: GistLocationBundle:POSLocations:editSubmit }

gist_loc_pos_locations_delete:
    pattern: /pos_location/{id}/delete
    methods: [GET]
    defaults: { _controller: GistLocationBundle:POSLocations:delete }

gist_loc_pos_locations_grid:
    pattern: /pos_locations/grid
    methods: [GET]
    defaults: { _controller: GistLocationBundle:POSLocations:grid }

gist_loc_pos_locations_ajax_ledger_entry:
    pattern: /pos_locations/ajax/ledger/{pos_location_id}/{amount}/{date}/{description}
    methods: [GET]
    defaults: { _controller: GistLocationBundle:POSLocations:ajaxLedgerAddEntry }

gist_loc_pos_locations_ajax_return_security_deposit:
    pattern: /pos_locations/ajax/ledger/{pos_location_id}/{type}
    methods: [GET]
    defaults: { _controller: GistLocationBundle:POSLocations:ajaxReturnDeposit }