parameters:
#    Gist_gallery.example.class: Gist\GalleryBundle\Example

services:
#    Gist_gallery.example:
#        class: %Gist_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
